POST https://warehouzitserver.onrender.com/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "kchi.a",
    "firstname": "kachi",
    "lastname": "afudoh",
    "email": "kachi.a@ascomaster.com",
    "phonenumber": "07067572151",
    "role": "spaceseeker",
    "password": "1234567890"
}